// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package query

import (
	uuid "github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthOauth struct {
	ID           uuid.UUID
	OpenID       string
	AccessToken  string
	RefreshToken pgtype.Text
	AllowSync    bool
	ValidUntil   pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type AuthPassword struct {
	ID           uuid.UUID
	PasswordHash string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type AuthUser struct {
	ID        uuid.UUID
	Email     string
	Username  string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type CalendarSchedule struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Period    pgtype.Range[pgtype.Timestamptz]
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type LocationLocation struct {
	ID        uuid.UUID
	QueryID   uuid.UUID
	Title     string
	Address   string
	Category  string
	MapX      int32
	MapY      int32
	DeletedAt pgtype.Timestamptz
}

type LocationQuery struct {
	ID        uuid.UUID
	Data      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
